title: Minigolf Physics
description: Measuring bounce coefficients with IR sensors
theme: jekyll-theme-cayman

markdown: kramdown
kramdown:
  math_engine: mathjax

# serve from /docs/
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
